### ISSUE TITLE
プロジェクトWebサイトをどうするか

### ISSUE THREAD

**Issue by nmaya** [TeraTermProject/osdn-download#7]
### 現状
OSDN の「プロジェクトWebページ」を使っている。
プロジェクトのサイトとオンラインマニュアルが含まれている。

SVNリポジトリから自動反映している。
| SVN | PATH | URL |
| ------------- | ------------------------------- | ----------------------- |
| trunk/doc/web | /home/groups/t/tt/ttssh2/htdocs | https://ttssh2.osdn.jp/ |
| trunk/doc/en | /home/groups/t/tt/ttssh2/htdocs/manual/5/en | https://ttssh2.osdn.jp/manual/5/en/ |
| trunk/doc/ja | /home/groups/t/tt/ttssh2/htdocs/manual/5/ja | https://ttssh2.osdn.jp/manual/5/ja/ |
| branches/4-stable/doc/en | /home/groups/t/tt/ttssh2/htdocs/manual/4/en | https://ttssh2.osdn.jp/manual/4/en/ |
| branches/4-stable/doc/ja | /home/groups/t/tt/ttssh2/htdocs/manual/4/ja | https://ttssh2.osdn.jp/manual/4/ja/ |

### 案1 GitHub Page
- プロジェクトWebサイト用にリポジトリを作成
  - /doc/web を持ってくる
- オンラインマニュアルの展開
  - 別のリポジトリの下層を接ぎ木した状態を持ってくるのは厳しそう
- osdn 側で .htaccess を書けば PATH を維持して新しい URL へ飛ばせる
```
# osdn から github へのリダイレクト
# https://ttssh2.osdn.jp/manual/4/ja/commandline/teraterm.html -> https://teratermproject.github.io/manual/4/ja/commandline/teraterm.html
# https://ttssh2.osdn.jp/manual/5/ja/usage/migrate_to_5.html -> https://teratermproject.github.io/manual/5/ja/usage/migrate_to_5.html
RewriteEngine on
RewriteRule ^(.*)$ https://teratermproject.github.io%{REQUEST_URI} [L,R=301]
```

### 案2 OSDN プロジェクトWebページ を使い続ける
- GitHub から clone して必要なものだけを展開する cron を動かす？
```
例：
git pull --rebase
git switch trunk
cp doc/web/index.html.ja /home/groups/t/tt/ttssh2/htdocs
cp doc/web/index.html.en /home/groups/t/tt/ttssh2/htdocs
cp doc/web/teraterm.css /home/groups/t/tt/ttssh2/htdocs
cp -r doc/en /home/groups/t/tt/ttssh2/htdocs/manual/5/en
cp -r doc/ja /home/groups/t/tt/ttssh2/htdocs/manual/5/ja
git switch branches/4-stable
cp -r doc/en /home/groups/t/tt/ttssh2/htdocs/manual/4/en
cp -r doc/ja /home/groups/t/tt/ttssh2/htdocs/manual/4/ja
```

### 案3 独自ドメインでサーバを立てる
- 費用のコストがかかる
- メンテする技術コストがかかる

### TODO
- [x] TeraTermProject.github.io を teraterm から更新
- [x] TeraTermProject.github.io の自動更新
- [x] https://ttssh2.osdn.net の自動更新元を修正
- [x] OSDNとGitHub Pageのどちらを正とするか決める
  - しばらく並列運用するなら
    - canonicalの設定
    - TeraTermProject/update_website/convert_utf8html.pl で差し込めるのではないか 
  - GitHub Pageに移転するなら
    - shell.osdn.jp の更新スクリプトを止める
    - 301リダイレクトをOSDNに仕込む
    - 移転のアナウンス
- [x] GitHub Pageを正とする
  - shell.osdn.jp の更新スクリプトを止める（止まってしまったので不可）
  - 301リダイレクトをOSDNに仕込む （止まってしまったので不可）
  - [x] 移転をアナウンス
  - [x] [ドキュメント等のURLを変更](https://github.com/TeraTermProject/teraterm/issues/33)
- [x] [ライセンスファイルなどを含めるようにする](https://github.com/TeraTermProject/teraterm/issues/35)
- [x] [/ の更新元を独立](https://github.com/TeraTermProject/teraterm/issues/34)
- [x] [wiki:プロジェクトページの更新手順](https://github.com/TeraTermProject/teraterm/wiki/Update-Project-page) を更新
  -  https://github.com/TeraTermProject/teraterm/issues/20

**Comment by zmatsuo** [comment]
試しに github.io の機能を使ってつくってみました。
https://github.com/zmatsuo/zmatsuo.github.io
teraterm/doc/web を置いています。

このURLからwebサイトとして見ることができます。
https://zmatsuo.github.io/

TeraTermProject.github.io というリポジトリを作れば
https://TeraTermProject.github.io/ からアクセスできるはずです。

うまくOSDNのサイトと同じような内容にできるか検討必要です。

index.html.ja, index.html.en は使えないようです。

manual/ をソースリポジトリから定期的にコピーすれば
ほぼ同じサイトが作れそうな感触です。

**Comment by nmaya** [comment]
テストありがとうございます。

> index.html.ja, index.html.en は使えないようです。

- index.html を日本語にして、英語の index-en.html へ誘導する（http://www.math.sci.hiroshima-u.ac.jp/m-mat/MT/SFMT/ の日英逆）
- 日本語にする必要もないくらいシンプルな英語のページにする

のどちらかですが、前者にしましょうか。

> manual/ をソースリポジトリから定期的にコピーすれば

なるほど、ソースのリポジトリの一部を github.io のリポジトリに自動コミットできれば、github.io のリポジトリから GitHub Page に自動的に反映されるというわけですね。

#14（メーリングリスト）のアーカイブを https://teratermproject.github.io/ 配下に置かなければ、これでよいと思います。

**Comment by zmatsuo** [comment]
現在のリポジトリからサイトを作りました。
https://teratermproject.github.io/

文字化けはしていますが、おおむねサイトは再現できていると思います。

次のスクリプトでサイトを作っています。
[update_website.sh.txt](https://github.com/TeraTermProject/osdn-download/files/12843330/update_website.sh.txt)

**Comment by nmaya** [comment]
ありがとうございます。

### 実行される仕組み
このスクリプト？は今までのように定期実行したり、「今すぐ実行」できるものなのでしょうか？
.github/workflows/xxx.yml ファイルはないようですし、[ここ](https://github.com/TeraTermProject/TeraTermProject.github.io/actions)を見てみましたが、どこに実行されるものがあるのかわかりませんでした。

### 文字化けの原因
ブラウザの文字コードの判定が「HTTP の `Content-Type: text/html; charset=` の値 > HTML の `<meta content="text/html; charset=` の値」なために文字化けが起きることがあります。
実際 `content-type: text/html; charset=utf-8` になっていて、HTML は `Shift_JIS` なので、前者が勝っているようです。

### 文字化けの対応
html ヘルプコンパイラで chm を生成するには Shift_JIS でないとうまくいかないため、doc/ja 配下の HTML の charset を変えることはできません。
Web サイトに反映するたびに自動で「文字コード変換」+「metaタグ書き替え」をすればいいのかもしれませんが、このスクリプトを実行するマシン？に、それができるツールが入っているでしょうか？

**Comment by zmatsuo** [comment]
手もとで実行して更新していました。

更新スクリプトを調整してupdate_websiteリポジトリにを置きました。
https://github.com/TeraTermProject/update_website

このリポジトリのActionsを実行すると
update_website.sh が実行されて、
teraterm-mirror-gitsvn リポジトリを元に
TeraTermProject.github.io リポジトリが更新されます。

**Comment by zmatsuo** [comment]
```
$ curl -s -i https://teratermproject.github.io/manual/5/ja/ | grep charset
content-type: text/html; charset=utf-8
<meta http-equiv="Content-Type" content="text/html; charset=Shift_JIS">
```
1つ目のcharsetがHTTPのレスポンス内で、
2つ目がhtmlファイル内ですね。

1つ目は、GitHub の web サーバーの動作ですね。

何らかの方法で、web サーバーの動作を変更できればいのですが。
もしかすると .gitattributes で変更できるかもしれないですが
ドキュメントで見つけることはできませんでした。

> Web サイトに反映するたびに自動で「文字コード変換」+「metaタグ書き替え」をすればいいのかもしれません

スクリプトでは単純にコピーしています。
そのあとに、nkfですべてのファイルの文字コードをUTF-8変換して、
(UTF-8で扱われるので) html内の charset= の変更はあきらめる
という強引な方法でもとりあえずokかもしれません。

> このスクリプトを実行するマシン？に、それができるツールが入っているでしょうか？

update_website の actions の環境は ubuntu-latest で
大抵のツールが使えると思います。
無ければ apt-get install すれば入りそうです。

**Comment by zmatsuo** [comment]
マニュアルのhtmlを文字コードの変換とcharsetの付け替えをおこなって
update_websiteリポジトリに置くように手を入れました。

文字化けせずにサイトを表示できるようになりました。
https://teratermproject.github.io/

毎日 04:15 JST (19.15 UTC) に teraterm-mirror-gitsvn リポジトリから
更新するようにしました。

**Comment by nmaya** [comment]
GitHub の [doc/web ](https://github.com/TeraTermProject/teraterm/tree/main/doc/web), [doc/en ](https://github.com/TeraTermProject/teraterm/tree/main/doc/en), [doc/ja ](https://github.com/TeraTermProject/teraterm/tree/main/doc/ja) を https://ttssh2.osdn.jp/ に持ってくる方法はありますか？

**Comment by nmaya** [comment]
### ttssh2.osdn.jp の現状

```
+------------------------------+
| svn.osdn.net                 |
|   [svn repository] -------------+
|     trunk/doc/web            |  |
|     trunk/doc/en             |  |
|     trunk/doc/ja             |  |
|     branches/4-stable/doc/en |  |
|     branches/4-stable/doc/ja |  |
+------------------------------+  |
                                  |
+----------------------+          |
| shell.osdn.net       |          |
|   [shell script] <--------------+
|     +-> /            | https://ttssh2.osdn.jp/
|         /manual/5/en |
|         /manual/5/ja |
|         /manual/4/en |
|         /manual/4/ja |
+----------------------+
```

### ステップ1

現状の https://teratermproject.github.io/

```
+--------------------------+
| TeraTermProject/teraterm |
|   [git repository] ---------------+
|     main/doc/web         |        |
|     main/doc/ja          |        |
|     main/doc/en          |        |
|     4-stable/doc/en      |        |
|     4-stable/doc/ja      |        |
+--------------------------+        |
                                    |
+--------------------------------+  |
| TeraTermProject/update_website |  |
|   [workflow]                   |  |
|     git clone <-------------------+
|     copy                       |
|     convert to utf8            |
|     git push --------------------------------+
|                                |             |
+--------------------------------+             |
                                               |
+-------------------------------------------+  |
| TeraTermProject/TeraTermProject.github.io |  |
|   [git repository] <-------------------------+
|     /                                     | https://teratermproject.github.io/
|     /manual/5/en                          |
|     /manual/5/ja                          |
|     /manual/4/en                          |
|     /manual/4/ja                          |
+-------------------------------------------+
```

現在自動更新はできていない https://github.com/TeraTermProject/teraterm/issues/20

### ステップ2

TeraTermProject/update_website のスクリプトで、ライセンスファイルを tar.gz から解凍して TeraTermProject.github.io に push する。

※これは後でもいい

### ステップ3

https://teratermproject.github.io/ とhttps://ttssh2.osdn.jp/ を同じ状態にしたい。

変換済みの TeraTermProject.github.io を osdn 側に clone すればよい。

```
+--------------------------+
| TeraTermProject/teraterm |
|   [git repository] ---------------+
|     main/doc/web         |        |
|     main/doc/ja          |        |
|     main/doc/en          |        |
|     4-stable/doc/en      |        |
|     4-stable/doc/ja      |        |
+--------------------------+        |
                                    |
+--------------------------------+  |
| TeraTermProject/update_website |  |
|   [workflow]                   |  |
|     git clone <-------------------+
|     copy                       |
|     convert to utf8            |
|     git push --------------------------------+
|                                |             |
+--------------------------------+             |
                                               |
+-------------------------------------------+  |
| TeraTermProject/TeraTermProject.github.io |  |
|   [git repository     ] <--------------------+
|     /               |                     | https://teratermproject.github.io/
|     /manual/5/en    |                     |
|     /manual/5/ja    +---+                 |
|     /manual/4/en        |                 |
|     /manual/4/ja        |                 |
+-------------------------+-----------------+
                          |
+----------------------+  |
| shell.osdn.net       |  |
|   [shell script]  <-----+
|     +-> /            | https://ttssh2.osdn.jp/
|         /manual/5/en |
|         /manual/5/ja |
|         /manual/4/en |
|         /manual/4/ja |
+----------------------+
```

### ステップ4

web の / 部分を tearterm リポジトリの doc から分離したい。

「TeraTermProject.github.io で管理」とも考えたが、別のリポジトリにしておいたほうがよさそう。

```
+--------------------------+
| TeraTermProject/web      |
|   [git repository] ---------------+
|     main/                |        |
+--------------------------+        |
                                    |
+--------------------------+        |
| TeraTermProject/teraterm |        |
|   [git repository] ---------------+
|     main/doc/ja          |        |
|     main/doc/en          |        |
|     4-stable/doc/en      |        |
|     4-stable/doc/ja      |        |
+--------------------------+        |
                                    |
+--------------------------------+  |
| TeraTermProject/update_website |  |
|   [workflow]                   |  |
|     git clone <-------------------+
|     copy                       |
|     convert to utf8            |
|     git push --------------------------------+
|                                |             |
+--------------------------------+             |
                                               |
+-------------------------------------------+  |
| TeraTermProject/TeraTermProject.github.io |  |
|   [git repository     ] <--------------------+
|     /               |                     | https://teratermproject.github.io/
|     /manual/5/en    |                     |
|     /manual/5/ja    +---+                 |
|     /manual/4/en        |                 |
|     /manual/4/ja        |                 |
+-------------------------+-----------------+
                          |
+----------------------+  |
| shell.osdn.net       |  |
|   [shell script]  <-----+
|     +-> /            | https://ttssh2.osdn.jp/
|         /manual/5/en |
|         /manual/5/ja |
|         /manual/4/en |
|         /manual/4/ja |
+----------------------+
```

**Comment by zmatsuo** [comment]
> https://teratermproject.github.io/ とhttps://ttssh2.osdn.jp/ を同じ状態にしたい。
> 変換済みの TeraTermProject.github.io を osdn 側に clone すればよい。

試してみました。
osdn.jp に https://teratermproject.github.io/ のコピーを作ってみました
https://ttssh2.osdn.jp/tmp/zmatsuo_test/TeraTermProject.github.io/

この要領で、OSDN の web サーバーのコンテンツを
GitHub と同期できそうです。

コピーを作った手順は次の通りです。

shell.osdn.net にログインして、
```
cd /home/groups/t/tt/ttssh2/htdocs/tmp
mkdir zmatsuo_test
cd zmatsuo_test
git clone https://github.com/TeraTermProject/TeraTermProject.github.io.git
```

**Comment by nmaya** [comment]
ありがとうございます。うまくコピーできていると思います。
スクリプトでは今までどおり `umask 002` をして、update_website に倣って git clone に `--depth 1` を付けてコピーすればよさそうです。

初回実行

```
umask 002
cd /home/groups/t/tt/ttssh2
git clone --branch master --depth 1 https://github.com/TeraTermProject/TeraTermProject.github.io.git htdocs
```

定期実行スクリプト

```
#!/bin/sh

DESTDIR=/home/groups/t/tt/ttssh2/htdocs

umask 002
cd $DESTDIR
/usr/bin/git pull --rebase
```

こんな感じ？

**Comment by zmatsuo** [comment]
OSDNで次のように修正を行いました。

- htdocsをhtdocs_orgにバックアップ
    cd /home/groups/t/tt/ttssh2
    mv htdocs htdocs_org
- 初回実行
    umask 002
    cd /home/groups/t/tt/ttssh2
    git clone --branch master --depth 1 https://github.com/TeraTermProject/TeraTermProject.github.io.git htdocs
- manual-checkout.sh をバックアップ
    cd bin/
    cp manual-checkout.sh manual-checkout_org.sh
- manual-checkout.sh を定期実行スクリプトの内容に変更
    #!/bin/sh

    DESTDIR=/home/groups/t/tt/ttssh2/htdocs

    umask 002
    cd $DESTDIR
    /usr/bin/git pull --rebase

https://ttssh2.osdn.jp/ の内容が
https://teratermproject.github.io/ と同等になりました。

/home/groups/t/tt/ttssh2/bin/manual-checkout.sh は定期的に呼ばれます。

**Comment by nmaya** [comment]
現在は OSDN のプロジェクトWebページ（https://ttssh2.osdn.jp ） が動いていますが、いずれ動かなくなる（SSL証明書の失効・サーバが動かなくなる・ドメインの失効・管理放棄されるなど）可能性を見越すのであれば、動いているうちに対応が必要です。

- 公にアナウンスする
- ドキュメントなどを「https://ttssh2.osdn.jp/ 」から「https://teratermproject.github.io/ 」へ変更
- 「https://ttssh2.osdn.jp/ 」側に .htaccess でリダイレクトを仕掛ける
  - OSDN が生きているうちにやらないと、検索エンジンや、アクセスして来た人たちが移転先を見つけられない

**Comment by zmatsuo** [comment]
Webページを移動を進めたほうが良いと思います。

https://teratermproject.github.io/ は
ページカウンタ(訪問者数)以外はうまく動いているんじゃないでしょうか。

**Comment by nmaya** [comment]
わかりました。ではこうなるようにします。

### 目標

```
+--------------------------+
| TeraTermProject/web      |
|   [git repository] ---------------+
|     main/                |        |
+--------------------------+        |
                                    |
+--------------------------+        |
| TeraTermProject/teraterm |        |
|   [git repository] ---------------+
|     main/doc/ja          |        |
|     main/doc/en          |        |
|     4-stable/doc/en      |        |
|     4-stable/doc/ja      |        |
+--------------------------+        |
                                    |
+--------------------------------+  |
| TeraTermProject/update_website |  |
|   [workflow]                   |  |
|     git clone <-------------------+
|     copy                       |
|     convert to utf8            |
|     git push --------------------------------+
|                                |             |
+--------------------------------+             |
                                               |
+-------------------------------------------+  |
| TeraTermProject/TeraTermProject.github.io |  |
|   [git repository     ] <--------------------+
|     /                                     | https://teratermproject.github.io/
|     /manual/5/en                          |      ^
|     /manual/5/ja                          |      |
|     /manual/4/en                          |      |
|     /manual/4/ja                          |      |
+-------------------------------------------+      |
                                                   |
+----------------------+                           |
| shell.osdn.net       |                           |
|   /.htaccess         | https://ttssh2.osdn.jp/ --+ redirect
+----------------------+
```

**Comment by zmatsuo** [comment]
https://ttssh2.osdn.jp/ が本当にダウンしてしまったようです。

検索エンジンに https://teratermproject.github.io/ を教えるような
策はあるでしょうか?

**Comment by nmaya** [comment]
簡単に効果が得られるものはない（あればSEO業者なんてものはないはず）と思います。
なので「生きているうちに」と書きました。

この状況でできることとして、Twitter アカウントの URL を変えました。
あとは移転のアナウンスをするのと、それをどこかに補足してもらうくらいでしょうか。

**Comment by nmaya** [comment]
このプロジェクトのURLも変更しました。

アナウンスはこんな感じにしようと思います。
```
プロジェクトWebサイト移転のお知らせ

Webサイトを OSDN で公開していましたが、Webサーバのレスポンスがなくなったため移転しました。
移転先は https://teratermproject.github.io/ です。
```

**Comment by zmatsuo** [comment]
アナウンスありがとうございます。

簡単にすぐに何とかできる方法ないですよね。

リソースなどのソース内の
https://ttssh2.osdn.jp/ を
https://teratermproject.github.io/ に
置き換えていこうかと思います。
